name: MRG_MacOS

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create Build Environment
      working-directory: ${{runner.workspace}}/Morrigu
      shell: bash
      run: mkdir build

    # Conan setup
    - name: Install conan
      shell: bash
      run: brew install conan

    - name: add conan to path
      shell: bash
      run: echo "::add-path::~/.local/bin"
    
    - name: configure conan new profile
      shell: bash
      run: conan profile new default --detect
    
    - name: configure conan C++ compiler
      shell: bash
      run: |
        conan profile update settings.compiler=apple-clang default
        conan profile update settings.compiler.version=11.0 default
    
    - name: add conan remotes
      shell: bash
      run: |
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan remote add ImGui-Docking https://api.bintray.com/conan/ithyx/imgui
    
    - name: conan install [DEBUG]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: conan install .. -s build_type=Debug --build=missing
    
    - name: conan install [Release]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: conan install .. -s build_type=Release --build=missing

    # Cmake setup
    - name: Configure CMake [DEBUG]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
    
    - name: Build [DEBUG]
      working-directory: ${{runner.workspace}}/Morrigu/build
      shell: bash
      run: cmake --build .
    
    - name: Configure CMake [RELEASE]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build [RELEASE]
      working-directory: ${{runner.workspace}}/Morrigu/build
      shell: bash
      run: cmake --build .
